[package]
name = "hpm5361-hal"
version = "0.1.0"
edition = "2021"
authors = ["Andelf <andelf@gmail.com>"]
repository = "https://github.com/andelf/hpm5361-hal"
documentation = "https://docs.rs/hpm5361-hal"
homepage = "https://github.com/andelf/hpm5361-hal"
categories = []
description = ""
keywords = []
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
riscv = { version = "0.11", features = ["critical-section-single-hart"] }
embedded-hal = { version = "1.0.0" }
hpm5361-pac = { version = "0.0.2", features = ["critical-section"] }
critical-section = "1.1.2"

[features]
default = []

hpm5300evk = []
hpm5301evklite = []

[dev-dependencies]
panic-halt = "0.2.0"
